CREATE TABLE ren_cms_Sub_Categories (
		CID UNIQUEIDENTIFIER NULL 
		, langCode VARCHAR (128) NOT NULL 
		, longName VARCHAR (255) NOT NULL 
		, PKID UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL 
		, ref VARCHAR (255) NOT NULL 
		, shortName VARCHAR (255) NOT NULL 
)
